configmap:
  cdx:
    name: cdx-account-service-registration
    eventhub:
      namespace: s00199-enscdx-pd-us-account-na1
      shared_access:
        keyname: enscdx-account-SASsendlisten
        password_kvkey: cdxevh-pd-us-access-key-account-na1
      ingestion_path_registration: evhcdx-account-registration
      path_dlq: evhcdx-account-dlq
    azure:
      tenant_id: ee69be27-d938-4eb5-8711-c5e69ca43718
      keyvault:
        host: s00199nkvt10001.vault.azure.net
        url: https://s00199nkvt10001.vault.azure.net
      encryptaes_secret_kvkey: cdxapi-pd-us-encryptaes-secret
      encryptiv_salt_kvkey: cdxapi-pd-us-encryptiv-salt
      payload:
        encryptaes_secret_kvkey: cdxapi-pd-us-encrypt-payload-aes-secret
        encryptiv_salt_kvkey: cdxapi-pd-us-encrypt-payload-iv-salt
    java_options: -Xmx512m -Xms512m -XX:+UseG1GC -server -XX:MaxMetaspaceSize=256m -javaagent:/opt/newrelic/newrelic.jar -Dnewrelic.config.app_name=CRM-CDX-NonProd-pi -Dnewrelic.config.license_key=72f7d43463aa9187ce4646f4019ea5bc06a741f6
    app_log_level: trace
    app_stdout_color: false

deployment:
  spec:
    replicas: 1
    minreadyseconds: 35
    strategy:
      type: RollingUpdate
      maxunavailable: 1
      maxsurge: 2
  app: cdx-account-service-registration
  container:
    image: image
    resources:
      memory:
        limits: 1Gi
        requests: 1Gi
      cpu:
        limits: "1"
        requests: "0.1"
    port:
      cdx: 7013
      healthz: 7030
    livenessprobe:
      httpget:
        path: /health
        port: healthz
      initialdelayseconds: 60
      periodseconds: 30
      timeoutseconds: 10
    readinessprobe:
      httpget:
        path: /health
        port: healthz
      initialdelayseconds: 60
      periodseconds: 30
      timeoutseconds: 10
  envform:
    name: cdx-account-service-registration
  envs:
    env1:
      name: 
      fieldref:
        apiversion: v1
        fieldpath: spec.nodeName
    env2:
      name: 
      secretkeyref:
        name: 
        key: 
    env3:
      name: 
      secretkeyref:
        name: 
        key: 
  imagepullsecrets:
    name: 

autoscale:
  spec:
    minreplicas: 1
    maxreplicas: 1
    targetcpuutil: 50