  values_keys.push('cdx_eventhub_consumer_group_stage')

configmap:
  cdx:
    name: cdx-account-processor-registration
    cassandra:
      hosts: 10.18.140.150,10.18.140.151,10.18.140.152
      keyspace: cust_usa_pd
      username: cdxapi_db_nprod
      password_kvkey: cdxapi-pd-us-db-password-key
      ssl_enabled: true
      truststore:
        path: /tmp/cassandra.truststore
        password_kvkey: cdxapi-pd-us-db-truststore-password-key
    eventhub:
      namespace: s00199-enscdx-pd-us-account-na1
      syndication_path: evhcdx-account-syndication
      shared_access:
        keyname: enscdx-account-SASsendlisten
        password_kvkey: cdxevh-pd-us-access-key-account-na1
      consumer_group_registration: evhcdx-account-registration-csg1
      ingestion_path_registration: evhcdx-account-registration
      storage:
        container_name: stccdx-evh-account
        name: s00199stapdusna1evhaccount
        kvkey: cdxevh-pd-us-sta-key-account-na1
      consumer_group_stage: evhcdx-account-staging-csg1
    azure:
      tenant_id: ee69be27-d938-4eb5-8711-c5e69ca43718
      keyvault:
        host: s00199nkvt10001.vault.azure.net
        url: https://s00199nkvt10001.vault.azure.net
      encryptaes_secret_kvkey: cdxapi-pd-us-encryptaes-secret
      encryptiv_salt_kvkey: cdxapi-pd-us-encryptiv-salt
      payload:
        encryptaes_secret_kvkey: cdxapi-pd-us-encrypt-payload-aes-secret
        encryptiv_salt_kvkey: cdxapi-pd-us-encrypt-payload-iv-salt
    java_options: -Xmx512m -Xms512m -XX:+UseG1GC -server -XX:MaxMetaspaceSize=256m -javaagent:/opt/newrelic/newrelic.jar -Dnewrelic.config.app_name=CRM-CDX-NonProd-pi -Dnewrelic.config.license_key=72f7d43463aa9187ce4646f4019ea5bc06a741f6
    eh_consumer:
      max_throttle_limit: 100
      time_out_in_minutes: 2
    akka_stream:
      parallelism: 1
      batch_size: 10
      batch_time_window_in_seconds: 1
    app_log_level: trace
    app_stdout_color: false

# New keys
  cdx_cassandra_password_version:
  cdx_cassandra_truststore_password_version:
  cdx_cassandra_xyz:
  cdx_eventhub_shared_access_password_kvkey_version:
  cdx_eventhub_path_reprocess:
  cdx_eventhub_shared_access_password_kvkey_version:
  cdx_eventhub_consumer_hostname:
  cdx_eventhub_consumer_group_create:
  cdx_eventhub_ingestion_path_create:
  cdx_eventhub_shared_access_password_kvkey_version:
  cdx_eventhub_storagecontainer_name:
  cdx_eventhub_storage_key_version:
  cdx_eventhub_path_dlq:
  cdx_eventhub_shared_access_password_kvkey_version:
  cdx_healthcheck_http_host:
  cdx_healthcheck_http_port:
  cdx_healthcheck_https_host:
  cdx_healthcheck_https_port:

deployment:
  spec:
    replicas: 1
    minreadyseconds: 35
    strategy:
      type: RollingUpdate
      maxunavailable: 1
      maxsurge: 2      
  app: cdx-account-processor-registration
  container:
    image: image
    resources:
      memory:
        limits: 1Gi
        requests: 1Gi
      cpu:
        limits: "1"
        requests: "0.1"
    port: 7030
    livenessprobe:
      httpget:
        path: /health
        port: 7030
      initialdelayseconds: 60
      periodseconds: 30
      timeoutseconds: 10
    readinessprobe:
      httpget:
        path: /health
        port: 7030
      initialdelayseconds: 60
      periodseconds: 30
      timeoutseconds: 10
  envform:
    name: cdx-account-processor-registration
  envs:
    env1:
      name: 
      fieldref:
        apiversion: v1
        fieldpath: metadata.name
    env2:
      name: 
      secretkeyref:
        name: 
        key: 
    env3:
      name: 
      secretkeyref:
        name: 
        key: 
    env4:
      name: 
      secretkeyref:
        name: 
        key: 
  imagepullsecrets:
    name: 

autoscale:
  spec:
    minreplicas: 1
    maxreplicas: 1
    targetcpuutil: 50